### ISSUE TITLE
go get gets stc that does not support new muxed account format

### ISSUE THREAD

**Issue by leighmcculloch** [xdrpp/stc#10]
When I run the go get install instructions below I get a version of stc that does not have muxed accounts implemented.
```
go get -u github.com/xdrpp/stc/cmd/stc
```

I can see that there is a commit on `master` that has muxed accounts, but it seems like that change hasn't been propagated to the `go1` branch which is where go get is pulling from.

As a side note, the go1 branch setup is pretty unique and not intuitive. I haven't seen any other Go project serve different code on master and go1.

**Comment by stanford-scs** [comment]
Resolved.
