### ISSUE TITLE
Add support for protocol 19 and P strkey

### ISSUE THREAD

**Issue by leighmcculloch** [xdrpp/stc#15]
Now that CAP-21 and CAP-40 are being implemented we should add the new xdr, which should be trivial, and add support for the new SEP-23 strkey for the CAP-40 signer.

The new xdr is available at the branch below. I gave it a quick try and it appears to work fine:
https://github.com/stellar/stellar-core/pull/3377
https://github.com/sisuresh/stellar-core branch `cap21-40-2`

The one thing that needs coding is the new `P` strkey, that is documented here:
https://github.com/stellar/stellar-protocol/pull/1014

**Comment by stanford-scs** [comment]
Added in release v0.2.0.
