### ISSUE TITLE
Error loading module requirements: unknown revision b257d8ace4e0

### ISSUE THREAD

**Issue by leevlad** [xdrpp/stc#3]
Building a project that uses the following version of Stellar Go SDK (and probably many others before it) fails due to unknown revision: `https://github.com/stellar/go/blob/f7c9e85f25a8e998eca1e046121a229de412d9ff/go.sum#L244`

```
go: github.com/xdrpp/stc@v0.0.0-20191113232203-b257d8ace4e0: unknown revision b257d8ace4e0
```

As you can see from the above modfile, it freezes `github.com/xdrpp/stc` at commit `b257d8ace4e0`. However, it appears this commit no longer exists in this repo?

Was the entire repository force-pushed over with new commit history?

Is there a way to get access to commit `b257d8ace4e0` so I can diff it against the current head?

**Comment by stanford-scs** [comment]
This issue should be resolvable now that there is an actual numbered release of stc.  If you are still experiencing the issue, please raise the issue in the stellar go repository.
